// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RpgUiTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AdventurePlayFeatureFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "AdventurePlayFeature", "\t| Taak                | Succesactie                   | Bevestigingsbericht     " +
                "            | Stats & level | Gerelateerde input field / knop | \r\n| - | --------" +
                "----------- | ----------------------------- | ----------------------------------" +
                "- | ------------- | ------------------------------- |\r\n| 1 | Clicker            " +
                " | 5 keer klikken                | *Great job! You levelled up*        | +1     " +
                "       | Disabled                        |\r\n| 2 | Uploader            | 1 keer b" +
                "estand uploaden       | *File selected, level up!*          | +1            | Di" +
                "sabled                        |\r\n| 3 | Typer               | `\"Lorem Ipsum\"` typ" +
                "en         | *Dolar sit amet!*                   | +1            | Disabled     " +
                "                   |\r\n| 4 | Slider              | Volledig naar rechts schuiven " +
                "| *Slid to the next level!*           | +1            | Disabled                " +
                "        |\r\n| 5 | Alle taken voltooid | Bovenstaande vier acties      | *You\'ve r" +
                "eached the highest level!* | n.v.t.        | n.v.t.                          |\r\n" +
                "\r\n- Nadat alle taken voltooit zijn, verschijnt de knop \"PLay again\". Klikken op " +
                "deze knop brengt je terug naar de PreparePlayPage\r\n\r\n**Aandachtspunten\r\n- In fea" +
                "ture file voor slider svp uitsluitend tientallen procenten opgeven als percentag" +
                "e, dus {0%, 10%, 20%, ..., 100%)\r\n- Scenario U2 Uploader - Klikken op \"bestand k" +
                "iezen\" en vervolgens klikken op \"Annuleren\" is niet te automatiseren. Daarom enk" +
                "el checken of corfirmation message en level up bij aanvang niet aanwezig zijn.\r\n" +
                "\r\n*****BONUS Easter Egg*****\r\nVia onderstaande tasks is het onbedoeld mogelijk m" +
                "isbruik te maken van een kwetsbaarheid in de code, waardoor je build maximale st" +
                "ats-waarden van 10 kunnen bereiken\r\n1. Typer\t\t-->\tDe uitschakeling van het eleme" +
                "nt na het typen van \"Lorem Ipsum\" kan worden teruggedraaid. Door opnieuw \"Lorem " +
                "Ipsum\" typen en dit proces te herhalen, kun je max stats bereiken.\r\n2. Uploader\t" +
                "\t--> De uitschakeling van het element na het uploaden van de \"cotton candy\" file" +
                " kan worden teruggedraaid. Door vervolgens de \"rock in the ocean\" te uploaden, \r" +
                "\n\t\t\t\t\topnieuw de uitschakeling van het element na het uploaden terug te draaien " +
                "en dit proces te herhalen, kun je max stats bereiken.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AdventurePlayFeature.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AdventurePlayFeature.feature.ndjson", 29);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Thief", "0", null, DisplayName="H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build(Thief,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Knight", "1", null, DisplayName="H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build(Knight,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Mage", "2", null, DisplayName="H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build(Mage,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Brigadier", "3", null, DisplayName="H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
            "op de adventure play page voor elke build(Brigadier,3)")]
        public async global::System.Threading.Tasks.Task H1DeGetoondeStatsOpDePreparePlayPageKomenOvereenMetDeGetoondeStatsOpDeAdventurePlayPageVoorElkeBuild(string buildType, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("BuildType", buildType);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H1 De getoonde stats op de prepare play page komen overeen met de getoonde stats " +
                    "op de adventure play page voor elke build", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.GivenAsync(string.Format("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                            "te komen met character build type \"{0}\"", buildType), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
 await testRunner.ThenAsync("komen de getoonde stats op de adventure page overeen met de getoonde stats van de" +
                        " prepare page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("clicker", "de Click it! button 5 keer wordt ingedrukt", "Thief", "4", null, DisplayName="H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1(clicker,de Click it! button 5 keer wordt" +
            " ingedrukt,Thief,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("uploader", "het \"cotton candy\" bestand wordt geüpload", "Knight", "5", null, DisplayName="H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1(uploader,het \"cotton candy\" bestand word" +
            "t geüpload,Knight,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("typer", "het bericht \"Lorem Ipsum\" wordt getypt", "Mage", "6", null, DisplayName="H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1(typer,het bericht \"Lorem Ipsum\" wordt ge" +
            "typt,Mage,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("slider", "de slider voor 100 procent naar rechts wordt geschoven", "Brigadier", "7", null, DisplayName="H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
            "oogt de waarde van stats en level met 1(slider,de slider voor 100 procent naar r" +
            "echts wordt geschoven,Brigadier,7)")]
        public async global::System.Threading.Tasks.Task H2EenVoltooiingVanDeTaskLeidtTotBijbehorendeConfirmationMessageEnVerhoogtDeWaardeVanStatsEnLevelMet1(string task, string action, string character, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Task", task);
            argumentsOfScenario.Add("Action", action);
            argumentsOfScenario.Add("Character", character);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H2 Een voltooiing van de task leidt tot bijbehorende confirmation message en verh" +
                    "oogt de waarde van stats en level met 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
 await testRunner.GivenAsync(string.Format("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                            "te komen met character build type \"{0}\"", character), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
 await testRunner.WhenAsync(string.Format("{0}", action), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
 await testRunner.ThenAsync(string.Format("verschijnt voor de task \"{0}\" het bijbehorende bevestigingsbericht", task), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
 await testRunner.AndAsync("zijn de waarden voor stats en level 1 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("clicker", "de Click it! button 5 keer wordt ingedrukt", "Thief", "8", null, DisplayName="H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt(clicker,de Click it! button 5 keer wordt ingedrukt,Thief,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("uploader", "het \"cotton candy\" bestand wordt geüpload", "Knight", "9", null, DisplayName="H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt(uploader,het \"cotton candy\" bestand wordt geüpload,Knight,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("typer", "het bericht \"Lorem Ipsum\" wordt getypt", "Mage", "10", null, DisplayName="H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt(typer,het bericht \"Lorem Ipsum\" wordt getypt,Mage,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("slider", "de slider voor 100 procent naar rechts wordt geschoven", "Brigadier", "11", null, DisplayName="H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
            " raakt(slider,de slider voor 100 procent naar rechts wordt geschoven,Brigadier,1" +
            "1)")]
        public async global::System.Threading.Tasks.Task H3EenVoltooiingVanDeTaskZorgtErVoorDatHetElementVanDieTaskDisabledRaakt(string task, string actionToCompleteTask, string character, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Task", task);
            argumentsOfScenario.Add("ActionToCompleteTask", actionToCompleteTask);
            argumentsOfScenario.Add("Character", character);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H3 Een voltooiing van de task zorgt er voor dat het element van die task disabled" +
                    " raakt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
 await testRunner.GivenAsync(string.Format("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                            "te komen met character build type \"{0}\"", character), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
 await testRunner.ThenAsync(string.Format("is het element van de task \"{0}\" enabled", task), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
 await testRunner.WhenAsync(string.Format("{0}", actionToCompleteTask), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
 await testRunner.ThenAsync(string.Format("is het element van de task \"{0}\" disabled", task), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H4 De Click it! button start met de tekst \'Click me 5 times\' en loopt per klik dy" +
            "namisch terug van 5 naar 0")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H4 De Click it! button start met de tekst \'Click me 5 times\' en loopt per klik dy" +
            "namisch terug van 5 naar 0")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task H4DeClickItButtonStartMetDeTekstClickMe5TimesEnLooptPerKlikDynamischTerugVan5Naar0()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H4 De Click it! button start met de tekst \'Click me 5 times\' en loopt per klik dy" +
                    "namisch terug van 5 naar 0", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Knight\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 67
 await testRunner.ThenAsync("loopt de dynamische teller in de click it button terug van 5 naar 0 bij elke klik" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H5 Het afronden van de vier tasks resulteert in een max level bevestigingsbericht" +
            ", verhoogt de waarde van stats en level met 4 en een knop om opnieuw te spelen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H5 Het afronden van de vier tasks resulteert in een max level bevestigingsbericht" +
            ", verhoogt de waarde van stats en level met 4 en een knop om opnieuw te spelen")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task H5HetAfrondenVanDeVierTasksResulteertInEenMaxLevelBevestigingsberichtVerhoogtDeWaardeVanStatsEnLevelMet4EnEenKnopOmOpnieuwTeSpelen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H5 Het afronden van de vier tasks resulteert in een max level bevestigingsbericht" +
                    ", verhoogt de waarde van stats en level met 4 en een knop om opnieuw te spelen", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Brigadier\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
 await testRunner.WhenAsync("de Click it! button 5 keer wordt ingedrukt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
 await testRunner.AndAsync("het \"cotton candy\" bestand wordt geüpload", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("het bericht \"Lorem Ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("de slider voor 100 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.ThenAsync("verschijnt het max level bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
 await testRunner.AndAsync("zijn de waarden voor stats en level 4 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U1 Clicker - Zo lang het totale aantal clicks op de Click it! button kleiner is d" +
            "an 5, resulteert deze actie niet in level up een bevestigingsbericht voor deze t" +
            "ask")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U1 Clicker - Zo lang het totale aantal clicks op de Click it! button kleiner is d" +
            "an 5, resulteert deze actie niet in level up een bevestigingsbericht voor deze t" +
            "ask")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task U1Clicker_ZoLangHetTotaleAantalClicksOpDeClickItButtonKleinerIsDan5ResulteertDezeActieNietInLevelUpEenBevestigingsberichtVoorDezeTask()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U1 Clicker - Zo lang het totale aantal clicks op de Click it! button kleiner is d" +
                    "an 5, resulteert deze actie niet in level up een bevestigingsbericht voor deze t" +
                    "ask", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 82
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Brigadier\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
 await testRunner.WhenAsync("de Click it! button 1 keer wordt ingedrukt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
 await testRunner.ThenAsync("verschijnt voor de task \"clicker\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.WhenAsync("de Click it! button 3 keer wordt ingedrukt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
 await testRunner.ThenAsync("verschijnt voor de task \"clicker\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
 await testRunner.WhenAsync("de Click it! button 1 keer wordt ingedrukt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
 await testRunner.ThenAsync("verschijnt voor de task \"clicker\" het bijbehorende bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
 await testRunner.AndAsync("zijn de waarden voor stats en level 1 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U2 Uploader - Zo lang er geen bestand is geüpload, is er geen level up een bevest" +
            "igingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U2 Uploader - Zo lang er geen bestand is geüpload, is er geen level up een bevest" +
            "igingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task U2Uploader_ZoLangErGeenBestandIsGeuploadIsErGeenLevelUpEenBevestigingsberichtVoorDezeTask()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U2 Uploader - Zo lang er geen bestand is geüpload, is er geen level up een bevest" +
                    "igingsbericht voor deze task", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Mage\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
 await testRunner.ThenAsync("verschijnt voor de task \"uploader\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.WhenAsync("het \"cotton candy\" bestand wordt geüpload", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
 await testRunner.ThenAsync("verschijnt voor de task \"uploader\" het bijbehorende bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
 await testRunner.AndAsync("zijn de waarden voor stats en level 1 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U3 Typer - Zo lang het woord \"Lorem Ipsum\" niet is getypt, resulteert deze actie " +
            "niet in level up een bevestigingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U3 Typer - Zo lang het woord \"Lorem Ipsum\" niet is getypt, resulteert deze actie " +
            "niet in level up een bevestigingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task U3Typer_ZoLangHetWoordLoremIpsumNietIsGetyptResulteertDezeActieNietInLevelUpEenBevestigingsberichtVoorDezeTask()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U3 Typer - Zo lang het woord \"Lorem Ipsum\" niet is getypt, resulteert deze actie " +
                    "niet in level up een bevestigingsbericht voor deze task", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Knight\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
 await testRunner.WhenAsync("het bericht \"lorem Ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
 await testRunner.ThenAsync("verschijnt voor de task \"typer\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.WhenAsync("het bericht \"Lorem ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
 await testRunner.ThenAsync("verschijnt voor de task \"typer\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 110
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.WhenAsync("het bericht \"lorem ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 112
 await testRunner.ThenAsync("verschijnt voor de task \"typer\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 113
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.WhenAsync("het bericht \"Lorem Ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
 await testRunner.ThenAsync("verschijnt voor de task \"typer\" het bijbehorende bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
 await testRunner.AndAsync("zijn de waarden voor stats en level 1 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U4 Slider - Zo lang de slider niet volledig naar rechts geschoven is, resulteert " +
            "deze actie niet in level up een bevestigingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U4 Slider - Zo lang de slider niet volledig naar rechts geschoven is, resulteert " +
            "deze actie niet in level up een bevestigingsbericht voor deze task")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task U4Slider_ZoLangDeSliderNietVolledigNaarRechtsGeschovenIsResulteertDezeActieNietInLevelUpEenBevestigingsberichtVoorDezeTask()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U4 Slider - Zo lang de slider niet volledig naar rechts geschoven is, resulteert " +
                    "deze actie niet in level up een bevestigingsbericht voor deze task", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 119
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 120
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Thief\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 121
 await testRunner.WhenAsync("de slider voor 20 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
 await testRunner.ThenAsync("verschijnt voor de task \"slider\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
 await testRunner.WhenAsync("de slider voor 40 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
 await testRunner.ThenAsync("verschijnt voor de task \"slider\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.WhenAsync("de slider voor 30 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
 await testRunner.ThenAsync("verschijnt voor de task \"slider\" geen bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 129
 await testRunner.AndAsync("zijn de waarden voor stats en level 0 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
 await testRunner.WhenAsync("de slider voor 10 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
 await testRunner.ThenAsync("verschijnt voor de task \"slider\" het bijbehorende bevestigingsbericht", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
 await testRunner.AndAsync("zijn de waarden voor stats en level 1 hoger dan bij aanvang op de adventure play " +
                        "page pagina", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U5 - Zo lang niet alle vier de taken zijn voltooid, is de Play again button niet " +
            "zichtbaar, wel als het voltooid is")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U5 - Zo lang niet alle vier de taken zijn voltooid, is de Play again button niet " +
            "zichtbaar, wel als het voltooid is")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        public async global::System.Threading.Tasks.Task U5_ZoLangNietAlleVierDeTakenZijnVoltooidIsDePlayAgainButtonNietZichtbaarWelAlsHetVoltooidIs()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U5 - Zo lang niet alle vier de taken zijn voltooid, is de Play again button niet " +
                    "zichtbaar, wel als het voltooid is", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 134
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 135
 await testRunner.GivenAsync("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                        "te komen met character build type \"Thief\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 136
 await testRunner.ThenAsync("is de \"Play again\" button niet zichtbaar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 137
 await testRunner.WhenAsync("de slider voor 100 procent naar rechts wordt geschoven", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 138
 await testRunner.ThenAsync("is de \"Play again\" button niet zichtbaar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 139
 await testRunner.WhenAsync("het \"cotton candy\" bestand wordt geüpload", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
 await testRunner.ThenAsync("is de \"Play again\" button niet zichtbaar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 141
 await testRunner.WhenAsync("het bericht \"Lorem Ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 142
 await testRunner.ThenAsync("is de \"Play again\" button niet zichtbaar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 143
 await testRunner.WhenAsync("de Click it! button 5 keer wordt ingedrukt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 144
 await testRunner.ThenAsync("is de \"Play again\" button wel zichtbaar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Thief", "8", "19", null, DisplayName="BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build(Thief,8,19)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Knight", "8", "20", null, DisplayName="BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build(Knight,8,20)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Mage", "9", "21", null, DisplayName="BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build(Mage,9,21)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Brigadier", "8", "22", null, DisplayName="BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
            "stats voor elke build(Brigadier,8,22)")]
        public async global::System.Threading.Tasks.Task BONUSEasterEggTyperMisbruikKwetsbaarheidTyperTaskResulteertInLevel10StatsVoorElkeBuild(string buildType, string aantal, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("BuildType", buildType);
            argumentsOfScenario.Add("Aantal", aantal);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BONUS Easter Egg Typer: Misbruik kwetsbaarheid typer task resulteert in level 10 " +
                    "stats voor elke build", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 147
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 148
 await testRunner.GivenAsync(string.Format("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                            "te komen met character build type \"{0}\"", buildType), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
 await testRunner.WhenAsync("het bericht \"Lorem Ipsum\" wordt getypt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
 await testRunner.AndAsync(string.Format("in totaal {0} keer de typer blokkade wordt uitgeschakeld en vervolgens het berich" +
                            "t \"Lorem Ipsum\" wordt getypt", aantal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
 await testRunner.ThenAsync("zijn de waarden voor alle stats gelijk aan level 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AdventurePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Thief", "4", "23", null, DisplayName="BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build(Thief,4,23)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Knight", "4", "24", null, DisplayName="BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build(Knight,4,24)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Mage", "5", "25", null, DisplayName="BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build(Mage,5,25)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Brigadier", "4", "26", null, DisplayName="BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
            "el 10 stats voor elke build(Brigadier,4,26)")]
        public async global::System.Threading.Tasks.Task BONUSEasterEggUploaderMisbruikKwetsbaarheidUploaderTaskResulteertInLevel10StatsVoorElkeBuild(string buildType, string aantal, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("BuildType", buildType);
            argumentsOfScenario.Add("Aantal", aantal);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BONUS Easter Egg Uploader: Misbruik kwetsbaarheid uploader task resulteert in lev" +
                    "el 10 stats voor elke build", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 161
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
 await testRunner.GivenAsync(string.Format("dat ik de juiste handelingen heb verricht om op de play adventure pagina terecht " +
                            "te komen met character build type \"{0}\"", buildType), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
 await testRunner.WhenAsync("het \"cotton candy\" bestand wordt geüpload", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
 await testRunner.AndAsync(string.Format("gedurende {0} iteraties wordt de uploaderblokkade uitgeschakeld met uploaden \"roc" +
                            "k in the ocean\" gevolgd door \"cotton candy\" bestand", aantal), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 165
 await testRunner.ThenAsync("zijn de waarden voor alle stats gelijk aan level 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
