// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RpgUiTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PreparePlayFeatureFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "PreparePlayFeature", "\t- Na het klikken op de \"Click here to play\" button, kom je terecht op de play pa" +
                "ge met de card \"Choose a name and build\"\r\n\t- Om het spel daadwerkelijk succesvol" +
                " te kunnen starten (door op de \'Start!\' button te klikken), moet een \'Character " +
                "name\' worden ingevuld. De build staat by default op \"Thief\", maar kan via de dro" +
                "pdown worden gewijzigd.\r\n\t- Na het succesvol klikken op de \"Start!\" button, kom " +
                "je terecht op de play page met de card \"Adventure time\".\r\n\t- Indien succesvol kl" +
                "ikken op de \"Start!\" button niet lukt, blijf je op de play page met de card \"Cho" +
                "ose a name and build\" en krijg je de validatie-errors te zien.\r\n\t- De character " +
                "name moet tussen de drie en twintig katakters zijn. De mogelijke errors zijn:\r\n\t" +
                "\t* Te kort: Name must be at least 3 characters\r\n\t\t* Te lang: Name cannot be long" +
                "er than 20 characters\r\n\t- Validatie-errors worden nóóit getoond zo lang de \"Star" +
                "t!\" button niet is ingedrukt. Ook niet als je een character name hebt ingevuld d" +
                "ie niet aan de voorwaarden voldoet.\r\n\t- Indien je als gevolg van het klikken op " +
                "de \"Start!\" button een validatie-error krijgt, deze waarde correct corrigeert en" +
                " vervolgens voorziet van invalide waarde, krijg je ze validatie-error direct te " +
                "zien zonder dat je hiervoor op de de \"Start!\" button moet klikken.\r\n\t- Via data " +
                "binding is de ingevulde character name en geselecteerde build direct zichtbaar i" +
                "n het overzicht. \r\n\t- Iedere build (Thief, Knight, Mage, Brigadier) heeft bij se" +
                "lectie vaste stats waarden (zie Domain folder), zichtbaar in FE wanneer build ge" +
                "selecteerd is. Thief is by default geselecteerd.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "PreparePlayFeature.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PreparePlayFeature.feature.ndjson", 10);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H1. Kies een geldige character name, selecteer een build en start het spel")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H1. Kies een geldige character name, selecteer een build en start het spel")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PreparePlayFeature")]
        public async global::System.Threading.Tasks.Task H1_KiesEenGeldigeCharacterNameSelecteerEenBuildEnStartHetSpel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H1. Kies een geldige character name, selecteer een build en start het spel", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync("ik op de button klik met de tekst \"Click here to play\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.ThenAsync("wordt de juiste pagina getoond met de card \"Choose a name and build\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table1.AddRow(new string[] {
                            "Spelersnaam",
                            "Brigadier"});
#line 18
 await testRunner.WhenAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table1, "When ");
#line hidden
#line 21
 await testRunner.AndAsync("ik op de button klik met de tekst \"Start!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.ThenAsync("wordt de juiste pagina getoond met de card \"Adventure time\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H2. De juiste error messages verschijnen en verdwijnen in de juiste situaties")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H2. De juiste error messages verschijnen en verdwijnen in de juiste situaties")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PreparePlayFeature")]
        public async global::System.Threading.Tasks.Task H2_DeJuisteErrorMessagesVerschijnenEnVerdwijnenInDeJuisteSituaties()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H2. De juiste error messages verschijnen en verdwijnen in de juiste situaties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
 await testRunner.GivenAsync("ik op de button klik met de tekst \"Click here to play\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table2.AddRow(new string[] {
                            "Hi",
                            "Mage"});
#line 27
 await testRunner.AndAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table2, "And ");
#line hidden
#line 30
 await testRunner.ThenAsync("zie ik geen character name error message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
 await testRunner.WhenAsync("ik op de button klik met de tekst \"Start!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
 await testRunner.ThenAsync("zie ik de character name error message: \"Name must be at least 3 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table3.AddRow(new string[] {
                            "HiHiHi",
                            "Mage"});
#line 33
 await testRunner.WhenAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table3, "When ");
#line hidden
#line 36
 await testRunner.ThenAsync("zie ik geen character name error message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table4.AddRow(new string[] {
                            "HiHiHiHiHiHiHiHiHiHiH",
                            "Mage"});
#line 37
 await testRunner.WhenAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table4, "When ");
#line hidden
#line 40
 await testRunner.ThenAsync("zie ik de character name error message: \"Name cannot be longer than 20 characters" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table5.AddRow(new string[] {
                            "HiHiHiHi",
                            "Mage"});
#line 41
 await testRunner.WhenAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table5, "When ");
#line hidden
#line 44
 await testRunner.ThenAsync("zie ik geen character name error message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("H3. Iedere geselecteerde build heeft eigen stats-waarden")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("H3. Iedere geselecteerde build heeft eigen stats-waarden")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PreparePlayFeature")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Spelersnaam123", "Thief", "2", null, DisplayName="H3. Iedere geselecteerde build heeft eigen stats-waarden(Spelersnaam123,Thief,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Spelersnaam234", "Knight", "3", null, DisplayName="H3. Iedere geselecteerde build heeft eigen stats-waarden(Spelersnaam234,Knight,3)" +
            "")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Spelersnaam345", "Mage", "4", null, DisplayName="H3. Iedere geselecteerde build heeft eigen stats-waarden(Spelersnaam345,Mage,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Spelersnaam456", "Brigadier", "5", null, DisplayName="H3. Iedere geselecteerde build heeft eigen stats-waarden(Spelersnaam456,Brigadier" +
            ",5)")]
        public async global::System.Threading.Tasks.Task H3_IedereGeselecteerdeBuildHeeftEigenStats_Waarden(string characterName, string buildType, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("CharacterName", characterName);
            argumentsOfScenario.Add("BuildType", buildType);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("H3. Iedere geselecteerde build heeft eigen stats-waarden", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
 await testRunner.GivenAsync("ik op de button klik met de tekst \"Click here to play\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table6.AddRow(new string[] {
                            string.Format("{0}", characterName),
                            string.Format("{0}", buildType)});
#line 49
 await testRunner.WhenAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table6, "When ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table7.AddRow(new string[] {
                            string.Format("{0}", characterName),
                            string.Format("{0}", buildType)});
#line 52
 await testRunner.ThenAsync("zie ik de juiste character name, build type en stats waarden in het overzicht", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U1. Spel proberen te starten met character name die te kort is resulteert in erro" +
            "r message")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U1. Spel proberen te starten met character name die te kort is resulteert in erro" +
            "r message")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PreparePlayFeature")]
        public async global::System.Threading.Tasks.Task U1_SpelProberenTeStartenMetCharacterNameDieTeKortIsResulteertInErrorMessage()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U1. Spel proberen te starten met character name die te kort is resulteert in erro" +
                    "r message", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
 await testRunner.GivenAsync("ik op de button klik met de tekst \"Click here to play\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table8.AddRow(new string[] {
                            "Hi",
                            "Mage"});
#line 67
 await testRunner.AndAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table8, "And ");
#line hidden
#line 70
 await testRunner.WhenAsync("ik op de button klik met de tekst \"Start!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
 await testRunner.ThenAsync("zie ik de character name error message: \"Name must be at least 3 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("U2. Spel proberen te starten met character name die te lang is resulteert in erro" +
            "r message")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("U2. Spel proberen te starten met character name die te lang is resulteert in erro" +
            "r message")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PreparePlayFeature")]
        public async global::System.Threading.Tasks.Task U2_SpelProberenTeStartenMetCharacterNameDieTeLangIsResulteertInErrorMessage()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("U2. Spel proberen te starten met character name die te lang is resulteert in erro" +
                    "r message", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("ik op de button klik met de tekst \"Click here to play\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "CharacterName",
                            "BuildType"});
                table9.AddRow(new string[] {
                            "HiHiHiHiHiHiHiHiHiHiH",
                            "Mage"});
#line 76
 await testRunner.AndAsync("dat ik de character name invul en een build selecteer met onderstaande details", ((string)(null)), table9, "And ");
#line hidden
#line 79
 await testRunner.WhenAsync("ik op de button klik met de tekst \"Start!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
 await testRunner.ThenAsync("zie ik de character name error message: \"Name cannot be longer than 20 characters" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
